# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "example.StringMessage" do
    optional :value, :string, 1
  end
  add_message "example.AddItemRequest" do
    optional :userId, :uint64, 1
    optional :itemType, :uint64, 2
    optional :itemQuantity, :int64, 3
    optional :orderId, :string, 4
    optional :source, :uint64, 5
    repeated :prptys, :message, 6, "example.Property"
    optional :itemName, :string, 7
  end
  add_message "example.Property" do
    optional :itemId, :string, 1
    optional :id, :uint64, 2
    optional :value, :int64, 3
    optional :info, :string, 4
  end
end

module Example
  StringMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("example.StringMessage").msgclass
  AddItemRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("example.AddItemRequest").msgclass
  Property = Google::Protobuf::DescriptorPool.generated_pool.lookup("example.Property").msgclass
end
