// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package example

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StringMessage struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMessage) Reset()         { *m = StringMessage{} }
func (m *StringMessage) String() string { return proto.CompactTextString(m) }
func (*StringMessage) ProtoMessage()    {}
func (*StringMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *StringMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMessage.Unmarshal(m, b)
}
func (m *StringMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMessage.Marshal(b, m, deterministic)
}
func (m *StringMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMessage.Merge(m, src)
}
func (m *StringMessage) XXX_Size() int {
	return xxx_messageInfo_StringMessage.Size(m)
}
func (m *StringMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StringMessage proto.InternalMessageInfo

func (m *StringMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AddItemRequest struct {
	UserId               uint64      `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ItemType             uint64      `protobuf:"varint,2,opt,name=itemType,proto3" json:"itemType,omitempty"`
	ItemQuantity         int64       `protobuf:"varint,3,opt,name=itemQuantity,proto3" json:"itemQuantity,omitempty"`
	OrderId              string      `protobuf:"bytes,4,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Source               uint64      `protobuf:"varint,5,opt,name=source,proto3" json:"source,omitempty"`
	Prptys               []*Property `protobuf:"bytes,6,rep,name=prptys,proto3" json:"prptys,omitempty"`
	ItemName             string      `protobuf:"bytes,7,opt,name=itemName,proto3" json:"itemName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddItemRequest) Reset()         { *m = AddItemRequest{} }
func (m *AddItemRequest) String() string { return proto.CompactTextString(m) }
func (*AddItemRequest) ProtoMessage()    {}
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *AddItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddItemRequest.Unmarshal(m, b)
}
func (m *AddItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddItemRequest.Marshal(b, m, deterministic)
}
func (m *AddItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddItemRequest.Merge(m, src)
}
func (m *AddItemRequest) XXX_Size() int {
	return xxx_messageInfo_AddItemRequest.Size(m)
}
func (m *AddItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddItemRequest proto.InternalMessageInfo

func (m *AddItemRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AddItemRequest) GetItemType() uint64 {
	if m != nil {
		return m.ItemType
	}
	return 0
}

func (m *AddItemRequest) GetItemQuantity() int64 {
	if m != nil {
		return m.ItemQuantity
	}
	return 0
}

func (m *AddItemRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *AddItemRequest) GetSource() uint64 {
	if m != nil {
		return m.Source
	}
	return 0
}

func (m *AddItemRequest) GetPrptys() []*Property {
	if m != nil {
		return m.Prptys
	}
	return nil
}

func (m *AddItemRequest) GetItemName() string {
	if m != nil {
		return m.ItemName
	}
	return ""
}

type Property struct {
	ItemId               string   `protobuf:"bytes,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Value                int64    `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Info                 string   `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Property) Reset()         { *m = Property{} }
func (m *Property) String() string { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()    {}
func (*Property) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Property) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Property.Unmarshal(m, b)
}
func (m *Property) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Property.Marshal(b, m, deterministic)
}
func (m *Property) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Property.Merge(m, src)
}
func (m *Property) XXX_Size() int {
	return xxx_messageInfo_Property.Size(m)
}
func (m *Property) XXX_DiscardUnknown() {
	xxx_messageInfo_Property.DiscardUnknown(m)
}

var xxx_messageInfo_Property proto.InternalMessageInfo

func (m *Property) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *Property) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Property) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Property) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*StringMessage)(nil), "example.StringMessage")
	proto.RegisterType((*AddItemRequest)(nil), "example.AddItemRequest")
	proto.RegisterType((*Property)(nil), "example.Property")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xb1, 0xae, 0xd3, 0x30,
	0x14, 0x86, 0x95, 0x34, 0x37, 0xb9, 0x75, 0x69, 0x05, 0x06, 0x8a, 0x15, 0x10, 0xaa, 0x2c, 0x21,
	0x95, 0x0e, 0x8d, 0x28, 0x5b, 0x37, 0x06, 0x86, 0x0e, 0x20, 0x48, 0x59, 0x10, 0x2c, 0x6e, 0x72,
	0x48, 0x2d, 0x35, 0x71, 0xb0, 0x9d, 0x8a, 0xac, 0xbc, 0x02, 0x8f, 0xc6, 0x13, 0x20, 0xf1, 0x20,
	0x28, 0xb6, 0x13, 0x6e, 0x87, 0x6e, 0xfe, 0xce, 0xf9, 0x75, 0xfe, 0x73, 0xf2, 0x07, 0x4d, 0x15,
	0xc8, 0x33, 0xcf, 0x60, 0x5d, 0x4b, 0xa1, 0x05, 0x8e, 0xe0, 0x07, 0x2b, 0xeb, 0x13, 0xc4, 0xcf,
	0x0a, 0x21, 0x8a, 0x13, 0x24, 0xac, 0xe6, 0x09, 0xab, 0x2a, 0xa1, 0x99, 0xe6, 0xa2, 0x52, 0x56,
	0x46, 0x5f, 0xa0, 0xe9, 0x5e, 0x4b, 0x5e, 0x15, 0xef, 0x40, 0x29, 0x56, 0x00, 0x7e, 0x84, 0x6e,
	0xce, 0xec, 0xd4, 0x00, 0xf1, 0x16, 0xde, 0x72, 0x9c, 0x5a, 0xa0, 0x7f, 0x3c, 0x34, 0x7b, 0x93,
	0xe7, 0x3b, 0x0d, 0x65, 0x0a, 0xdf, 0x1b, 0x50, 0x1a, 0xcf, 0x51, 0xd8, 0x28, 0x90, 0xbb, 0xdc,
	0x28, 0x83, 0xd4, 0x11, 0x8e, 0xd1, 0x2d, 0xd7, 0x50, 0x7e, 0x6a, 0x6b, 0x20, 0xbe, 0xe9, 0x0c,
	0x8c, 0x29, 0xba, 0xd7, 0xbd, 0x3f, 0x36, 0xac, 0xd2, 0x5c, 0xb7, 0x64, 0xb4, 0xf0, 0x96, 0xa3,
	0xf4, 0xa2, 0x86, 0x09, 0x8a, 0x84, 0xcc, 0xcd, 0xe0, 0xc0, 0xac, 0xd0, 0x63, 0xe7, 0xa8, 0x44,
	0x23, 0x33, 0x20, 0x37, 0xd6, 0xd1, 0x12, 0x7e, 0x89, 0xc2, 0x5a, 0xd6, 0xba, 0x55, 0x24, 0x5c,
	0x8c, 0x96, 0x93, 0xcd, 0x83, 0xb5, 0xbb, 0x7d, 0xfd, 0x41, 0x8a, 0x1a, 0xa4, 0x6e, 0x53, 0x27,
	0xe8, 0x97, 0x7b, 0xcf, 0x4a, 0x20, 0x91, 0x99, 0x3e, 0x30, 0xfd, 0x8a, 0x6e, 0x7b, 0x7d, 0x67,
	0xd5, 0xd5, 0xdd, 0x71, 0xe3, 0xd4, 0x11, 0x9e, 0x21, 0x9f, 0xe7, 0xee, 0x2c, 0x9f, 0xe7, 0xff,
	0xbf, 0x96, 0xbd, 0xc4, 0x02, 0xc6, 0x28, 0xe0, 0xd5, 0x37, 0xe1, 0xf6, 0x37, 0xef, 0xcd, 0x01,
	0x4d, 0x3e, 0x8b, 0x46, 0xee, 0x6d, 0x48, 0x78, 0x8f, 0x82, 0xb7, 0xd9, 0x51, 0xe0, 0xf9, 0xb0,
	0xeb, 0x45, 0x0c, 0xf1, 0x95, 0x3a, 0x7d, 0xfa, 0xf3, 0xf7, 0xdf, 0x5f, 0xfe, 0x63, 0x7a, 0x3f,
	0x39, 0xbf, 0x4a, 0x9c, 0x24, 0x81, 0xec, 0x28, 0xb6, 0xde, 0x6a, 0x53, 0x0e, 0x21, 0xf5, 0x36,
	0x5f, 0x50, 0xe4, 0x2a, 0xf8, 0xc9, 0x30, 0xf1, 0x32, 0xc8, 0xf8, 0x5a, 0x83, 0x3e, 0x37, 0x5e,
	0x84, 0x3e, 0xbc, 0xeb, 0xc5, 0xac, 0x66, 0xeb, 0xad, 0x0e, 0xa1, 0xf9, 0x85, 0x5e, 0xff, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0x19, 0xd2, 0xf1, 0x48, 0x7a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// YourServiceClient is the client API for YourService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type YourServiceClient interface {
	Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error)
}

type yourServiceClient struct {
	cc *grpc.ClientConn
}

func NewYourServiceClient(cc *grpc.ClientConn) YourServiceClient {
	return &yourServiceClient{cc}
}

func (c *yourServiceClient) Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/example.YourService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YourServiceServer is the server API for YourService service.
type YourServiceServer interface {
	Echo(context.Context, *StringMessage) (*StringMessage, error)
}

func RegisterYourServiceServer(s *grpc.Server, srv YourServiceServer) {
	s.RegisterService(&_YourService_serviceDesc, srv)
}

func _YourService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YourServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.YourService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YourServiceServer).Echo(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _YourService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.YourService",
	HandlerType: (*YourServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _YourService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// AddItemServiceClient is the client API for AddItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddItemServiceClient interface {
	AddItem(ctx context.Context, in *AddItemRequest, opts ...grpc.CallOption) (*AddItemRequest, error)
}

type addItemServiceClient struct {
	cc *grpc.ClientConn
}

func NewAddItemServiceClient(cc *grpc.ClientConn) AddItemServiceClient {
	return &addItemServiceClient{cc}
}

func (c *addItemServiceClient) AddItem(ctx context.Context, in *AddItemRequest, opts ...grpc.CallOption) (*AddItemRequest, error) {
	out := new(AddItemRequest)
	err := c.cc.Invoke(ctx, "/example.AddItemService/AddItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddItemServiceServer is the server API for AddItemService service.
type AddItemServiceServer interface {
	AddItem(context.Context, *AddItemRequest) (*AddItemRequest, error)
}

func RegisterAddItemServiceServer(s *grpc.Server, srv AddItemServiceServer) {
	s.RegisterService(&_AddItemService_serviceDesc, srv)
}

func _AddItemService_AddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddItemServiceServer).AddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.AddItemService/AddItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddItemServiceServer).AddItem(ctx, req.(*AddItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddItemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.AddItemService",
	HandlerType: (*AddItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddItem",
			Handler:    _AddItemService_AddItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
